# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7caeb45b583de2bae612da40381be618b41ca15aebae7a4ef13459286388d90d7da8e54d7f63d34fe03e2eb76a3ef287dbc0da90f0941220b109d392e17e4f36

test:
  secret_key_base: d2c7990a14984e248b1b2d4ee5f4775abde40a503a60fc733273d2bbcadf1b08d28a6cfe38d445e730b6fd4662521c37751a26933286cc318ddffbab34b8d683

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
